### PR TITLE
Support Mac OS style line ending

### PR DESCRIPTION
**Pull request by kuzmas**
OS X style line ending is just '\r'.
This patch adds support for this line ending style.

### CODE REVIEW

**Comment by ColinH** [comment]
Actually "\r" is Mac OS up to OS 9. Mac OS X is Unix-based it uses Unix line ending, "\n". That said, you are not the first person to ask for "\r"-support. We will check your patch, thank you!

**Comment by ColinH** [comment]
Changing the `eol`-rule is not enough, the `input`-classes count `\n`-characters to determine the current line number, which is used for `parse_error` exceptions. I wanted to check out another, unrelated change regarding the line number counting and will try to add support for `\r`, too.

**Comment by kuzmas** [comment]
Oh, yeah, you are absolutely right - it's OS 9, not OS X. It just happened that I use OS X at work and we still have a lot of files with "\r" in our projects.

**Comment by ColinH** [comment]
This will take some more work to do in a way that reported line numbers are always correct. I opened #22 as reminder and will close this pull-request.

**Comment by kuzmas** [comment]
Ok

**Pull request closed without merging**
